//Package passwordbox provides a textbox that hides its input with dots.
package passwordbox

import (
	"github.com/qlova/seed/user"
	"github.com/qlova/seed/user/password"

	"github.com/qlova/seed"
	"github.com/qlova/seed/script"
	"github.com/qlova/seeds/textbox"
)

func init() {
	var js, _ = Asset("argon2.js")

	seed.Embed("/dist/argon2.js", js)

	seed.Embed("/argon2-browser.js", []byte(Lib))

	var wasm, _ = Asset("argon2.wasm")

	seed.Embed("/argon2.wasm", wasm)
}

//Seed is a passwordbox.
type Seed struct {
	textbox.Seed
}

//New passwordbox.
func New() Seed {
	var PasswordBox = textbox.New()

	PasswordBox.SetAttributes("type='password'")
	PasswordBox.Require("/argon2-browser.js")

	return Seed{PasswordBox}
}

//AddTo parent.
func AddTo(parent seed.Interface) Seed {
	var PasswordBox = New()
	parent.Root().Add(PasswordBox)
	return PasswordBox
}

//Ctx is the script context to this seed.
type Ctx struct {
	textbox.Ctx
	with script.Args
}

//Ctx returns the script context to this seed.
func (passwordbox Seed) Ctx(q script.Ctx) Ctx {
	return Ctx{passwordbox.Seed.Ctx(q), nil}
}

//Hash returns a securely hashed passkey promise from the password box.
//The hostname is used as a salt, so do not change the hostname or users will be unable to login.
func (passwordbox Ctx) Hash() script.Promise {
	var q = passwordbox.Q
	var value = passwordbox.Ctx.Value()
	q.Javascript(passwordbox.Element() + `.hashedValue = ` + passwordbox.Element() + `.value;`)
	return q.Value(`argon2.hash({
		// required
		pass: ` + value.LanguageType().Raw() + `,
		salt: window.location.hostname,

		time: 1,
		mem: 1024*64,
		hashLen: 32,
		parallelism: 1,
		type: argon2.ArgonType.Argon2di,
		distPath: '' // asm.js script location, without trailing slash
	}).then(function(result) {
		` + passwordbox.Element() + `.hashedValue = result.hashHex;
		return result.hashHex;
	})`).Promise()
}

//HashedValue returns the hash value previously generated by Hash().
func (passwordbox Ctx) HashedValue() script.String {
	var q = passwordbox.Q
	return q.Value(passwordbox.Element() + ".hashedValue").String()
}

//With returns a context with the provided args used for HashAndGo calls.
func (passwordbox Ctx) With(args script.Args) Ctx {
	passwordbox.with = args
	return passwordbox
}

//HashAndGo hashes and then runs the function f with the user and hash as arguments.
func (passwordbox Ctx) HashAndGo(f func(user.User, password.Hash)) script.Promise {
	var q = passwordbox.Q
	return passwordbox.Hash().Then(func(d script.Dynamic) {
		q.Return(q.With(script.Args{
			"hash": passwordbox.HashedValue(),
		}).With(passwordbox.with).Go(func(u user.User) {
			f(u, password.Hash(u.Args("hash").String()))
		}))
	})
}
